-- LETS MIGRATE;
INSERT INTO migratedTestTable
SELECT 
CAST(REPLACE(CAST(CONV(SUBSTRING(CAST(SHA(CONCAT(id,'{YOUR_DB_NAME}',UUID_SHORT())) AS CHAR), 1, 16), 16, 10) AS SIGNED INTEGER),'-','') AS CHAR(20)) as id,
data1,
data2,
enabled
FROM {YOUR_DB_NAME}.testTable;